version: "2.1"
services:
  eureka-service-discovery:
    build: ./eureka-service-discovery
    ports:
      - 8090:8090
  producer1:
    build: ./producer
    ports:
     - 8080:8080
    depends_on:
      - eureka-service-discovery
    links:
      - eureka-service-discovery
  producer2:
    build: ./producer
    ports:
     - 8085:8080
    depends_on:
      - eureka-service-discovery
      - rabbit
    links:
      - eureka-service-discovery
      - rabbit
  consumer:
    build: ./consumer
    ports:
     - 8081:8081
    depends_on:
     - eureka-service-discovery
     - rabbit
    links:
     - eureka-service-discovery
     - rabbit
  netflix-zuul:
    build: ./netflix-zuul
    ports:
     - 8079:8079
    depends_on:
     - eureka-service-discovery
    links:
     - eureka-service-discovery
  rabbit:
     container_name: rabbit
     hostname: rabbit
     image: rabbitmq:3.6.6-management
     environment:
        - RABBITMQ_DEFAULT_USER = user
        - RABBITMQ_DEFAULT_PASS = user
     ports:
        - 5672:5672
        - 15672:15672

